services:
  bot:
    build: ./bot
    container_name: telegram_bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - USE_WEBHOOK=${USE_WEBHOOK}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - CHANNEL_ID=${CHANNEL_ID}
      - CSV_FILE_PATH=${CSV_FILE_PATH:-/app/logs/message_mapping.csv}
    networks:
      - bot_network
    volumes:
      - ./logs:/app/logs

  nginx:
    image: nginx:alpine
    container_name: telegram_bot_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - bot
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge
